#!/bin/bash

set -e

CREATE DATABASE IF NOT EXISTS \'${DB_NAME}\';
CREATE USER IF NOT EXISTS \'${DB_USER}\';
IDENTIFIED BY \'${DB_PASSWORD}\';

GRANT ALL PRIVILEGES
ON 'wordpress'.* 
TO 'wpuser';

FLUSH PRIVILEGES;

exec "$@"
